site_name: My Projects

theme:
  name: material

nav:
  - Home: index.md
  - Projects:
      - "Premier League Statistics Analysis (2021–2025)": projects/premier-league-stats-2021-2025-analysis.md
      - "Aplication for Failure Prediction": projects/application_for_failure_prediction.md
