site_name: Jakub Cwigon Data Science Portfolio

theme:
  name: material

nav:
  - Home: index.md
  - Projects:
      - "Premier League Statistics Analysis (2021–2025)": projects/premier-league-stats-2021-2025-analysis.md
      - "Second Project": projects/second-project.md
